id: P009136
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD90023
  title: ཧོང་ཡོན་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    860abe2e14204132aa1313d0d2bde96f:
      image_group_id: I1PD90092
      title: ''
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
